#!/bin/bash
#
action=$1

# now shift the positional parameters to the right, past
# the plug-in action, so that they can be pasted to the
# built-in actions.
#
shift

[ "$action" = "usage" ] && {
    sed -e 's/^    //' <<EndUsage
      cd [todo|addons|cfg]
        Changes the current directory to the directory
        holding the todo.txt and done.txt files (todo),
        the directory holding the addons (addons),
        or the directory holding the todo.cfg file (cfg).
        Defaults to the directory holding todo.txt.
EndUsage
  exit
}

# see which argument, if any was specified
#
if [ x"$1" == x ] ; then
  TODO_CD_TO_="$TODO_DIR"
elif echo "$1" | grep -iq ^todo$ ; then
  TODO_CD_TO_="$TODO_DIR"
elif echo "$1" | grep -iq ^addons$ ; then
  TODO_CD_TO_="$HOME"/.todo.actions.d
elif echo "$1" | grep -iq ^cfg$ ; then
  TODO_CD_TO_=$(echo "$TODOTXT_CFG_FILE" | sed 's|\(.*\)/todo.cfg|\1|')
else
  echo "'$1' is an invalid argument."
  exit
fi

# prefix spaces with backslash
#
TODO_CD_TO_=$(echo "$TODO_CD_TO_" | sed 's|[[:space:]]|\\ |g')

# change to the directory
#
echo "cd $TODO_CD_TO_"
exit
