#!/bin/bash
#
action=$1
shift

[ "$action" = "usage" ] && {
  echo "  did:" 
  echo "    like add, but adds the task as already done."
  echo "" 
  exit
}

if "$TODO_SH" command add "$@"; then
    # getting the number item: it's simply the last item added to the file
    line=`wc -l "$TODO_FILE" | sed "s/^[[:space:]]*//" | cut -d' ' -f1`
    echo "line is " $line
    "$TODO_SH" command do $line 
fi

